### ISSUE TITLE
vagrant up  Server load failed nginx report 502 error

### ISSUE THREAD

**Issue by SummerMagic** [svpernova09/EnterpriseHomestead#28]
==> EnterpriseHomestead: Running provisioner: shell...
    EnterpriseHomestead: Running: inline script
==> EnterpriseHomestead: Running provisioner: shell...
    EnterpriseHomestead: Running: script: Checking for old Schedule
==> EnterpriseHomestead: Running provisioner: shell...
    EnterpriseHomestead: Running: script: Clear Variables
==> EnterpriseHomestead: Running provisioner: shell...
    EnterpriseHomestead: Running: script: Restarting Cron
==> EnterpriseHomestead: Running provisioner: shell...
    EnterpriseHomestead: Running: script: Restarting Nginx
    EnterpriseHomestead: Job for php56-php-fpm.service failed because the control process exited with error code. See "systemctl status php56-php-fpm.service" and "journalctl -xe" for details.
    EnterpriseHomestead: Job for php70-php-fpm.service failed because the control process exited with error code. See "systemctl status php70-php-fpm.service" and "journalctl -xe" for details.
    EnterpriseHomestead: Job for php71-php-fpm.service failed because the control process exited with error code. See "systemctl status php71-php-fpm.service" and "journalctl -xe" for details.
==> EnterpriseHomestead: Running provisioner: shell...
    EnterpriseHomestead: Running: script: Creating MySQL Database: homestead
==> EnterpriseHomestead: Running provisioner: shell...
    EnterpriseHomestead: Running: script: Creating Postgres Database: homestead
==> EnterpriseHomestead: Running provisioner: shell...
    EnterpriseHomestead: Running: script: Update Composer
    EnterpriseHomestead: You are already using composer version 1.6.5 (stable channel).
==> EnterpriseHomestead: Running provisioner: shell...
    EnterpriseHomestead: Running: /var/folders/vn/jc12562x7dz44ggzk4w3_py40000gn/T/vagrant-shell20180620-58912-ipxd98.sh
==> EnterpriseHomestead: Running provisioner: shell...
    EnterpriseHomestead: Running: /var/folders/vn/jc12562x7dz44ggzk4w3_py40000gn/T/vagrant-shell20180620-58912-1v2chz2.sh
➜  EnterpriseHomestead git:(master) ✗

**Comment by SummerMagic** [comment]
Server load failed nginx report 502 error

**Comment by svpernova09** [comment]
Please open a new issue and fill out the issue template. Any debugging based on the little you've shown will be pure guesswork.
